name: biovitality
description: Plant disease recognition app.


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3

  image: ^3.2.0
  flutter_tflite: ^1.0.1
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_database: ^10.4.7
  http:
  image_editor:
  geolocator: ^7.7.1
  splashscreen:

    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  fl_chart: ^0.36.0
  google_maps_flutter: ^2.0.10
  url_launcher: ^6.0.10
  google_sign_in: ^6.2.1
  firebase_storage:
  geocoding:
  intl:
  dcdg:


dev_dependencies:
  flutter_test:
    sdk: flutter


    





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Tanmay_final_model.tflite
    - assets/model_apple.tflite
    - assets/apple_labels.txt
    - assets/model_banana.tflite
    - assets/banana_labels.txt
    - assets/model_chili.tflite
    - assets/chili_labels.txt
    - assets/model_citrus.tflite
    - assets/citrus_labels.txt
    - assets/model_corn.tflite
    - assets/corn_labels.txt
    - assets/model_cotton.tflite
    - assets/cotton_labels.txt
    - assets/model_grape.tflite
    - assets/grape_labels.txt
    - assets/model_mango.tflite
    - assets/mango_labels.txt
    - assets/model_papaya.tflite
    - assets/papaya_labels.txt
    - assets/model_potato.tflite
    - assets/potato_labels.txt
    - assets/model_rice.tflite
    - assets/rice_labels.txt
    - assets/model_tea.tflite
    - assets/tea_labels.txt
    - assets/model_tomato.tflite
    - assets/tomato_labels.txt
    - assets/model_rose.tflite
    - assets/rose_label.txt
    - assets/images/
    - assets/crops/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
